### ISSUE TITLE
Stopped working after last docker update

### ISSUE THREAD

**Issue by RedJohn14** [ajoergensen/docker-postsrsd#2]
Hello, I have been using this container for many months without any problems. However, since the last "docker compose pull" this container is causing problems. In the postfix log I keep getting the entry `"postfix/cleanup[699]: warning: connect to TCP map 172.22.1.42:10001: Connection refused"` and `"postfix/smtpd[410]: warning: connect to TCP map 172.22.1.42:10002: Connection refused".` I did the configuration as on the page and did not change anything. What could be the problem? [Implementing SRS with Mailcow](https://nowhere.dk/articles/implementing-srs-with-mailcow/)

Thanks for any help!

**Comment by FingerlessGlov3s** [comment]
@RedJohn14  see https://github.com/ajoergensen/docker-postsrsd/pull/3 I have made the changes required to fix this working again for Mailcow and what lines you need to change in your postfix configuration.

**Comment by ajoergensen** [comment]
I have merged the changes from @FingerlessGlov3s
